/*
 * vcu_config.h
 *
 *  Created on: 17 May 2026
 *      Author: mehta
 */

#ifndef INC_CONFIG_VCU_CONFIG_H_
#define INC_CONFIG_VCU_CONFIG_H_

#include "stm32f4xx_hal.h"

#define MIN_ADC_VAL 30
#define MAX_ADC_VAL 3070

#define TORQUE_LIM_POS 1000
#define TORQUE_LIM_NEG -100

#define INVERTER_TORQUE_COMMAND_CAN_TRANSMIT_RATE pdMS_TO_TICKS(20) // 50Hz

#define RTD_BUTTON_PRESS_MILLISECONDS pdMS_TO_TICKS(200)
#define RTD_BUZZER_TIME_MILLISECONDS pdMS_TO_TICKS(3000)
#define CALIBRATION_ENABLE_PERIOD_MILLISECONDS pdMS_TO_TICKS(3000)
#define PEDALS_FAULT_TIMEOUT_MILLISECONDS pdMS_TO_TICKS(100)

#define CALIBRATION_DATA_READY (1U << 0)
#define CALIBRATION_DATA_RECEIVED (1U << 1)

#define NO_ERRORS 0
#define APPS_1_OUT_OF_RANGE (1U << 0)
#define APPS_2_OUT_OF_RANGE (1U << 1)
#define BSE_OUT_OF_RANGE (1U << 2)

#define BRAKES_ENGAGED_THRESHOLD_PERCENTAGE 5

#endif /* INC_CONFIG_VCU_CONFIG_H_ */
